version: "3"

services:
  frontend:
    build:
      context: ./client/
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    links:
      - backend:server

  backend:
    build:
      context: ./server/
    restart: always
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: "true"
